default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: Queenriyana1
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: dashboard

test:
  <<: *default
  database: dashboard

production:
  <<: *default
  database: dashbaord
  